# Forward Pass


Here we created a forward pass method, that we need the:
1. MATRIX (input data) with the (a,b) shape 
2. The WEIGHTS with the (n,m) shape


And their shape should be compatible for the dot product operation (We multiply the columnX from HEIGHTS in every row), here (b == n). The dot product will give us an output with the shape (a,m), which is the output of the forward pass (Z).


In [11]:
import numpy as np


    # !------------------------------------------! Create the Matrix !------------------------------------------!
matrix = np.random.randint(1,10, size=(10, 3)) # That means 10 samples and 3 features
print(f"Input matrix (10x3):\n{matrix}\n")

    # !------------------------------------------! Create the Weights !------------------------------------------!
weights = np.random.rand(3, 1) # Here we create the weight for each feature
print(f"Weights matrix (3x1):\n{weights}\n")


Z = np.dot(matrix, weights)
print(f"Output of the forward pass Z (10x1):\n{Z}\n their shape is {Z.shape}")
# Here we dot the weights in the matrix, each column of the weight gonna dot each row in the matrix



Input matrix (10x3):
[[9 8 2]
 [4 8 2]
 [9 3 3]
 [3 9 6]
 [9 9 1]
 [4 1 1]
 [1 8 9]
 [5 8 5]
 [8 7 4]
 [4 3 8]]

Weights matrix (3x1):
[[0.07397176]
 [0.66681179]
 [0.56694672]]

Output of the forward pass Z (10x1):
[[ 7.1341336 ]
 [ 6.7642748 ]
 [ 4.36702136]
 [ 9.6249017 ]
 [ 7.23399867]
 [ 1.52964555]
 [10.51098654]
 [ 8.53908671]
 [ 7.52724348]
 [ 6.83189615]]
 their shape is (10, 1)



# Loss Function


In this part, we will create the target values (the expected output) and then calculate the loss using the Mean Squared Error (MSE) formula. The MSE is calculated as the average of the squared differences between the predicted values (Z) and the target values.
for subtraction operation in matrices, we need to make sure that the shapes of the matrices are compatible. In this case, Z has a shape of (100, 1) and targets also has a shape of (100, 1), so we can directly subtract them without any issues.





In [17]:
    # !------------------------------------------! Create the Target Values !------------------------------------------!
targets = np.random.rand(10, 1) # Here we simulate the target for each sample, how we created before 10 samples, we need 10 targets
print(f"Target values (10x1):\n{targets}\n")

    # !------------------------------------------! Calculate the Loss !------------------------------------------!
MSELoss = np.mean((Z - targets) ** 2) # Here we get the loss function to know the error of the model, the shape of the target and the Z need to be the same
print(f"Mean Squared Error Loss: {MSELoss:.2f}\n")

Target values (10x1):
[[0.03740205]
 [0.35238362]
 [0.90933158]
 [0.32177818]
 [0.85652206]
 [0.69486729]
 [0.86891199]
 [0.45596656]
 [0.35446476]
 [0.10159726]]

Mean Squared Error Loss: 48.64



# For the next steps see /2. Calculus
- BackPropagation
- Gradient Descent
- Optimization